experiment_name: "tdtoptw_dqn"
run_name: "qsa_multiday_v1"

data:
  pois_geoparquet: "data/gold/pois.geoparquet"
  knn_drive_time_graph_df: "data/gold/knn_drive_time_graph_df.csv"

env:
  start_poi_idx: 0
  start_day: 0
  day_start_minute: 480   # 8:00
  day_end_minute: 1380    # 23:00
  num_days: 3
  max_steps: 150

dqn:
  hidden_dim: 256
  gamma: 0.99
  lr: !!float 5e-5
  batch_size: 64
  replay_size: 100000
  num_episodes: 500
  epsilon_start: 1.0
  epsilon_end: 0.15
  epsilon_decay_episodes: 1000

reward:
  travel_penalty: -0.05
  distance_penalty: -0.1
  diversity_bonus: 0.2
  time_usage_bonus: 0.01
  step_bonus: 5.0
  invalid_penalty: -5.0
  night_penalty: -10.0
